database:
  driver: "SQL Server"
  port: "1433"
  server: "server_name"
  database: "database_name"
  trusted_connection: "yes"

logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    detailed:
      format: "%(asctime)s - %(levelname)s - %(filename)s:%(lineno)s - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: detailed
    file:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: detailed
      filename: "log/etl.log"
      maxBytes: 10485760  # 10MB
      backupCount: 5
  root:
    handlers: [console, file]
    level: INFO